## Project 2 Data Cleaning

Goals:
    
    - Import and examine data
    - Make structural changes to the data, identify variables that will need to be converted into numerics and drop NaN data
    - save as new csv
    
Note: The data was retrieved andf initial cleaning performed in the Data Acquisition Notebook. Due  to the size anad format of the data, I downloaded it manually, rather than programatically, so that it could be reformatted and saved. That file is the one used here.

In [1]:
import pandas as pd #work with dataframes
import numpy as np #perform mathematical manipulations
import time
start_time = time.time()

In [2]:
#due to data size the original csv could not be loaded into github
df = pd.read_csv("./NatalityData.csv", low_memory = False)

In [3]:
df.head()

,Unnamed: 0,BFACIL,MAGER,MBSTATE_REC,RESTATUS,MRACE15,MHISPX,MAR_P,DMAR,MEDUC,...,CA_GAST,CA_LIMB,CA_CLEFT,CA_CLPAL,CA_DOWN,CA_DISOR,CA_HYPO,ITRAN,ILIVE,BFED
0,0,1,29,1,1,3,0,X,1.0,4,...,N,N,N,N,N,N,N,N,Y,Y
1,1,1,40,2,1,10,0,X,1.0,7,...,N,N,N,N,N,N,N,N,Y,Y
2,2,1,30,1,1,3,0,X,1.0,5,...,N,N,N,N,N,N,N,N,Y,Y
3,3,1,25,1,1,1,0,X,1.0,6,...,N,N,N,N,N,N,N,N,Y,Y
4,4,1,38,1,1,1,0,Y,2.0,7,...,N,N,N,N,N,N,N,N,Y,Y

Inital import and examination of the data looks good. Next I will drop the preserved index (unnamed:0) and any rows that are all NA

In [4]:
df.drop('Unnamed: 0', axis = 1, inplace = True)

In [5]:
df.describe()

,BFACIL,MAGER,MBSTATE_REC,RESTATUS,MRACE15,MHISPX,DMAR,MEDUC,FAGECOMB,FRACE15,...,RF_CESARN,ME_PRES,RDMETH_REC,ATTEND,PAY,APGAR5,APGAR10,DPLURAL,COMBGEST,DBWT
count,3.757582e+06,3.757582e+06,3.757582e+06,3.757582e+06,3.757582e+06,3.757582e+06,3.309929e+06,3.757582e+06,3.757582e+06,3.757582e+06,...,3.757582e+06,3.757582e+06,3.757582e+06,3.757582e+06,3.757582e+06,3.757582e+06,3.757582e+06,3.757582e+06,3.757582e+06,3.757582e+06
mean,1.036010e+00,2.911359e+01,1.231216e+00,1.337152e+00,1.958608e+00,6.523033e-01,1.403336e+00,4.437099e+00,3.959935e+01,1.983849e+01,...,3.386146e-01,1.078217e+00,1.796375e+00,1.346222e+00,1.825797e+00,9.123753e+00,8.709228e+01,1.033927e+00,3.857770e+01,3.261057e+03
std,3.211681e-01,5.810794e+00,4.265969e-01,5.366699e-01,2.715571e+00,1.572964e+00,4.905671e-01,1.812613e+00,2.237607e+01,3.773056e+01,...,3.448253e+00,4.926309e-01,1.172924e+00,7.838421e-01,1.219623e+00,5.686681e+00,8.861702e+00,1.864191e-01,2.945069e+00,6.249298e+02
min,1.000000e+00,1.200000e+01,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+01,1.000000e+00,...,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.700000e+01,2.270000e+02
25%,1.000000e+00,2.500000e+01,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,3.000000e+00,2.800000e+01,1.000000e+00,...,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,9.000000e+00,8.800000e+01,1.000000e+00,3.800000e+01,2.955000e+03
50%,1.000000e+00,2.900000e+01,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,4.000000e+00,3.300000e+01,1.000000e+00,...,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,9.000000e+00,8.800000e+01,1.000000e+00,3.900000e+01,3.290000e+03
75%,1.000000e+00,3.300000e+01,1.000000e+00,2.000000e+00,2.000000e+00,0.000000e+00,2.000000e+00,6.000000e+00,3.800000e+01,4.000000e+00,...,0.000000e+00,1.000000e+00,3.000000e+00,1.000000e+00,2.000000e+00,9.000000e+00,8.800000e+01,1.000000e+00,4.000000e+01,3.623000e+03
max,9.000000e+00,5.000000e+01,3.000000e+00,4.000000e+00,1.500000e+01,9.000000e+00,2.000000e+00,9.000000e+00,9.900000e+01,9.900000e+01,...,9.900000e+01,9.000000e+00,9.000000e+00,9.000000e+00,9.000000e+00,9.900000e+01,9.900000e+01,5.000000e+00,9.900000e+01,9.999000e+03

In [6]:
df.shape

(3757582, 87)

In [7]:
df.dropna(inplace = True)

In [8]:
df.shape

(3309929, 87)

In [9]:
df['DPLURAL'].value_counts()

1    3199925
2     107014
3       2858
4         96
5         36
Name: DPLURAL, dtype: int64

In [10]:
df.drop_duplicates(inplace = True)

In [11]:
df.shape

(3309710, 87)

In [12]:
#Check to make sure this doesn't just remove duplicates based on plural pregnancies
df['DPLURAL'].value_counts()

1    3199885
2     106841
3       2852
4         96
5         36
Name: DPLURAL, dtype: int64

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3309710 entries, 0 to 3757581
Data columns (total 87 columns):
 #   Column       Dtype
---  ------       -----
 0   BFACIL       int64
 1   MAGER        int64
 2   MBSTATE_REC  int64
 3   RESTATUS     int64
 4   MRACE15      int64
 5   MHISPX       int64
 6   MAR_P        object
 7   DMAR         float64
 8   MEDUC        int64
 9   FAGECOMB     int64
 10  FRACE15      int64
 11  FHISPX       int64
 12  FEDUC        int64
 13  PRIORLIVE    int64
 14  PRIORDEAD    int64
 15  PRIORTERM    int64
 16  ILLB_R       int64
 17  PRECARE      int64
 18  PREVIS       int64
 19  WIC          object
 20  CIG_0        int64
 21  CIG_1        int64
 22  CIG_2        int64
 23  CIG_3        int64
 24  BMI          float64
 25  WTGAIN       int64
 26  RF_PDIAB     object
 27  RF_GDIAB     object
 28  RF_PHYPE     object
 29  RF_GHYPE     object
 30  RF_EHYPE     object
 31  RF_PPTERM    object
 32  RF_INFTR     object
 33  RF_FEDRG     object
 34  RF_ARTEC     object
 35  RF_CESARN    int64
 36  IP_GON       object
 37  IP_SYPH      object
 38  IP_CHLAM     object
 39  IP_HEPB      object
 40  IP_HEPC      object
 41  OB_ECVS      object
 42  OB_ECVF      object
 43  LD_INDL      object
 44  LD_AUGM      object
 45  LD_STER      object
 46  LD_ANTB      object
 47  LD_CHOR      object
 48  LD_ANES      object
 49  ME_PRES      int64
 50  ME_TRIAL     object
 51  RDMETH_REC   int64
 52  MM_MTR       object
 53  MM_PLAC      object
 54  MM_RUPT      object
 55  MM_UHYST     object
 56  MM_AICU      object
 57  ATTEND       int64
 58  MTRAN        object
 59  PAY          int64
 60  APGAR5       int64
 61  APGAR10      int64
 62  DPLURAL      int64
 63  SEX          object
 64  COMBGEST     int64
 65  DBWT         int64
 66  AB_AVEN1     object
 67  AB_AVEN6     object
 68  AB_NICU      object
 69  AB_SURF      object
 70  AB_ANTI      object
 71  AB_SEIZ      object
 72  CA_ANEN      object
 73  CA_MNSB      object
 74  CA_CCHD      object
 75  CA_CDH       object
 76  CA_OMPH      object
 77  CA_GAST      object
 78  CA_LIMB      object
 79  CA_CLEFT     object
 80  CA_CLPAL     object
 81  CA_DOWN      object
 82  CA_DISOR     object
 83  CA_HYPO      object
 84  ITRAN        object
 85  ILIVE        object
 86  BFED         object
dtypes: float64(2), int64(32), object(53)
memory usage: 2.2+ GB

Each of the object variables above will need to be encoded for the clustering model I use during preprocessing. I will do this in the exploratory analysis notebook directly to preserve the labels.

In [14]:
#check for any remaining nulls
for i in df.isnull().sum():
    print(i)

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0

In [15]:
#drop unknowns for categorical or numeric data for which it is not informative (i.e. Race)

df = df[df['BFACIL'] != 9]
df = df[df['MBSTATE_REC'] != 3]
df = df[df['MAR_P'] != 'U']
df = df[df['DMAR'] != 9]
df = df[df['MEDUC'] != 9]
df = df[df['FAGECOMB'] != 99]
df = df[df['PRIORLIVE'] != 99]
df = df[df['PRIORDEAD'] != 99]
df = df[df['PRIORTERM'] != 99]
df = df[df['ILLB_R'] != 999]
df = df[df['PREVIS'] != 99]
df = df[df['WIC'] != 'U']
df = df[df['CIG_0'] != 99]
df = df[df['CIG_1'] != 99]
df = df[df['CIG_2'] != 99]
df = df[df['CIG_3'] != 99]
df = df[df['BMI'] != 99.9]
df = df[df['WTGAIN'] != 99]
df = df[df['RF_PDIAB'] != 'U']
df = df[df['RF_GDIAB'] != 'U']
df = df[df['RF_PHYPE'] != 'U']
df = df[df['RF_GHYPE'] != 'U']
df = df[df['RF_EHYPE'] != 'U']
df = df[df['RF_PPTERM'] != 'U']
df = df[df['RF_INFTR'] != 'U']
df = df[df['RF_FEDRG'] != 'U']
df = df[df['RF_ARTEC'] != 'U']
df = df[df['RF_CESARN'] != 99]
df = df[df['IP_GON'] != 'U']
df = df[df['IP_SYPH'] != 'U']
df = df[df['IP_CHLAM'] != 'U']
df = df[df['IP_HEPB'] != 'U']
df = df[df['IP_HEPC'] != 'U']
df = df[df['OB_ECVS'] != 'U']
df = df[df['OB_ECVF'] != 'U']
df = df[df['LD_INDL'] != 'U']
df = df[df['LD_AUGM'] != 'U']
df = df[df['LD_STER'] != 'U']
df = df[df['LD_ANTB'] != 'U']
df = df[df['LD_CHOR'] != 'U']
df = df[df['LD_ANES'] != 'U']
df = df[df['ME_PRES'] != 9]
df = df[df['ME_TRIAL'] != 'U']
df = df[df['RDMETH_REC'] != 9]
df = df[df['MM_MTR'] != 'U']
df = df[df['MM_PLAC'] != 'U']
df = df[df['MM_RUPT'] != 'U']
df = df[df['MM_UHYST'] != 'U']
df = df[df['MM_AICU'] != 'U']
df = df[df['APGAR5'] != 99]
df = df[df['APGAR10'] != 99]
df = df[df['COMBGEST'] != 99]
df = df[df['DBWT'] != 9999]
df = df[df['AB_AVEN1'] != 'U']
df = df[df['AB_AVEN6'] != 'U']
df = df[df['AB_NICU'] != 'U']
df = df[df['AB_SURF'] != 'U']
df = df[df['AB_ANTI'] != 'U']
df = df[df['AB_SEIZ'] != 'U']
df = df[df['CA_ANEN'] != 'U']
df = df[df['CA_MNSB'] != 'U']
df = df[df['CA_CCHD'] != 'U']
df = df[df['CA_CDH'] != 'U']
df = df[df['CA_OMPH'] != 'U']
df = df[df['CA_GAST'] != 'U']
df = df[df['CA_LIMB'] != 'U']
df = df[df['CA_CLEFT'] != 'U']
df = df[df['CA_CLPAL'] != 'U']
df = df[df['CA_DOWN'] != 'U']
df = df[df['CA_DISOR'] != 'U']
df = df[df['CA_HYPO'] != 'U']
df = df[df['ITRAN'] != 'U']
df = df[df['ILIVE'] != 'U']
df = df[df['BFED'] != 'U']

In [16]:
df.shape

(2564260, 87)

Finally, I will rename the variables to more informative titles.

In [17]:
df.rename({
    'BFACIL':'Birth Place', 
    'MAGER':'Maternal Age',
    'MBSTATE_REC': 'Maternal Nativity',
    'RESTATUS': 'Maternal Residence Status', 
    'MRACE15': 'Maternal Race',
    'MHISPX':'Maternal Hispanic Origin',
    'MAR_P': 'Paternity Acknowledged',
    'DMAR': 'Marital Status',
    'MEDUC': 'Maternal Education',
    'FAGECOMB': 'Paternal Age',
    'FRACE15': 'Paternal Race',
    'FHISPX': 'Paternal Hispanic Origin',
    'FEDUC': 'Paternal Education',
    'PRIORLIVE': 'Prior births, now living',
    'PRIORDEAD': 'Prior births, now dead',
    'PRIORTERM':'Prior terminations',
    'ILLB_R': 'Interval since last Live Birth (Mo)', 
    'PRECARE': 'Month prenatal care Began',
    'PREVIS': 'Number of Prenatal Visits',
    'WIC': 'WIC',
    'CIG_0': 'Daily Cigarette use before Pregnancy',
    'CIG_1': 'Daily Cigarette use, 1st Trimester',
    'CIG_2': 'Daily Cigarette use, 2nd Trimester',
    'CIG_3': 'Daily Cigarette use, 3rd Trimester',
    'BMI':'BMI',
    'WTGAIN': 'Weight Gain',
    'RF_PDIAB': 'Pre-pregnancy Diabetes',
    'RF_GDIAB': 'Gestational Diabetes',
    'RF_PHYPE': 'Pre-pregnancy Hypertension',
    'RF_GHYPE': 'Gestational Hypertension',
    'RF_EHYPE': 'Hypertension Eclampsia',
    'RF_PPTERM':'Previous Preterm Birth',
    'RF_INFTR': 'Infertility treatment used',
    'RF_FEDRG': 'Fertility Enhancing Drugs',
    'RF_ARTEC': 'Asst. Reproductive Tech',
    'RF_CESARN':'Number of Previous Cesareans',
    'IP_GON': 'Gonorrhea',
    'IP_SYPH': 'Syphilis',
    'IP_CHLAM': 'Chlamydia',
    'IP_HEPB': 'Hep B',
    'IP_HEPC':'Hep C',
    'OB_ECVS':'Successful External Cephalic Version',
    'OB_ECVF':'Failed Cephalic Version',
    'LD_INDL':'Induced Labor',
    'LD_AUGM':'Augmented Labor',
    'LD_STER':'Steroids',
    'LD_ANTB':'Antibiotics',
    'LD_CHOR':'Chorioamnionitis',
    'LD_ANES':'Anesthesia',
    'ME_PRES':'Fetal Presentation at Delivery',
    'ME_TRIAL':'If Cesarean, Labor Attempted',
    'RDMETH_REC':'Delivery Method',
    'MM_MTR':'Maternal Transfusion',
    'MM_PLAC':'Perineal Laceration',
    'MM_RUPT':'Ruptured Uterus',
    'MM_UHYST':'Unplanned Hysterectomy',
    'MM_AICU':'Maternal admit to ICU',
    'ATTEND':'Attendant at Birth',
    'MTRAN':'Mother Transferred',
    'PAY':'Payment Source', 
    'APGAR5':'5 Minute APGAR',
    'APGAR10':'10 Minute APGAR',
    'DPLURAL':'Plurality (Number of Babies)',
    'SEX':'infant sex',
    'COMBGEST':'Gestation Duration (wks)',
    'DBWT':'Birth Weight (g)',
    'AB_AVEN1': 'Assisted Ventilation immediately',
    'AB_AVEN6': 'Assisted ventilation >6hr',
    'AB_NICU': 'Admission to NICU',
    'AB_SURF': 'Surffactant',
    'AB_ANTI': 'Antibiotis for Newborn',
    'AB_SEIZ': 'Seizures',
    'CA_ANEN': 'Anencephaly',
    'CA_MNSB': 'Spina Bifida',
    'CA_CCHD':'Cyanotic Congenital Heart Disease',
    'CA_CDH': 'Congenital Diaphragmatic Hernia',
    'CA_OMPH': 'Omphalocele',
    'CA_GAST':'Gastroschisis',
    'CA_LIMB': 'Limb Reduction Defect',
    'CA_CLEFT': 'Cleft lip',
    'CA_CLPAL': 'Cleft Palate',
    'CA_DOWN': 'Down Syndrome',
    'CA_DISOR': 'Suspected Chromosomal Disorder',
    'CA_HYPO': 'Hypospadias',
    'ITRAN': 'Infant Transferred',
    'ILIVE': 'Infant Living',
    'BFED': 'Infant Breastfed'
    },
    axis = 1, inplace = True)

In [18]:
df['Marital Status']

1          1.0
2          1.0
3          1.0
5          2.0
6          1.0
          ...
3757576    2.0
3757577    2.0
3757578    1.0
3757579    1.0
3757580    1.0
Name: Marital Status, Length: 2564260, dtype: float64

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2564260 entries, 1 to 3757580
Data columns (total 87 columns):
 #   Column                                Dtype
---  ------                                -----
 0   Birth Place                           int64
 1   Maternal Age                          int64
 2   Maternal Nativity                     int64
 3   Maternal Residence Status             int64
 4   Maternal Race                         int64
 5   Maternal Hispanic Origin              int64
 6   Paternity Acknowledged                object
 7   Marital Status                        float64
 8   Maternal Education                    int64
 9   Paternal Age                          int64
 10  Paternal Race                         int64
 11  Paternal Hispanic Origin              int64
 12  Paternal Education                    int64
 13  Prior births, now living              int64
 14  Prior births, now dead                int64
 15  Prior terminations                    int64
 16  Interval since last Live Birth (Mo)   int64
 17  Month prenatal care Began             int64
 18  Number of Prenatal Visits             int64
 19  WIC                                   object
 20  Daily Cigarette use before Pregnancy  int64
 21  Daily Cigarette use, 1st Trimester    int64
 22  Daily Cigarette use, 2nd Trimester    int64
 23  Daily Cigarette use, 3rd Trimester    int64
 24  BMI                                   float64
 25  Weight Gain                           int64
 26  Pre-pregnancy Diabetes                object
 27  Gestational Diabetes                  object
 28  Pre-pregnancy Hypertension            object
 29  Gestational Hypertension              object
 30  Hypertension Eclampsia                object
 31  Previous Preterm Birth                object
 32  Infertility treatment used            object
 33  Fertility Enhancing Drugs             object
 34  Asst. Reproductive Tech               object
 35  Number of Previous Cesareans          int64
 36  Gonorrhea                             object
 37  Syphilis                              object
 38  Chlamydia                             object
 39  Hep B                                 object
 40  Hep C                                 object
 41  Successful External Cephalic Version  object
 42  Failed Cephalic Version               object
 43  Induced Labor                         object
 44  Augmented Labor                       object
 45  Steroids                              object
 46  Antibiotics                           object
 47  Chorioamnionitis                      object
 48  Anesthesia                            object
 49  Fetal Presentation at Delivery        int64
 50  If Cesarean, Labor Attempted          object
 51  Delivery Method                       int64
 52  Maternal Transfusion                  object
 53  Perineal Laceration                   object
 54  Ruptured Uterus                       object
 55  Unplanned Hysterectomy                object
 56  Maternal admit to ICU                 object
 57  Attendant at Birth                    int64
 58  Mother Transferred                    object
 59  Payment Source                        int64
 60  5 Minute APGAR                        int64
 61  10 Minute APGAR                       int64
 62  Plurality (Number of Babies)          int64
 63  infant sex                            object
 64  Gestation Duration (wks)              int64
 65  Birth Weight (g)                      int64
 66  Assisted Ventilation immediately      object
 67  Assisted ventilation >6hr             object
 68  Admission to NICU                     object
 69  Surffactant                           object
 70  Antibiotis for Newborn                object
 71  Seizures                              object
 72  Anencephaly                           object
 73  Spina Bifida                          object
 74  Cyanotic Congenital Heart Disease     object
 75  Congenital Diaphragmatic Hernia       object
 76  Omphalocele                           object
 77  Gastroschisis                         object
 78  Limb Reduction Defect                 object
 79  Cleft lip                             object
 80  Cleft Palate                          object
 81  Down Syndrome                         object
 82  Suspected Chromosomal Disorder        object
 83  Hypospadias                           object
 84  Infant Transferred                    object
 85  Infant Living                         object
 86  Infant Breastfed                      object
dtypes: float64(2), int64(32), object(53)
memory usage: 1.7+ GB

In [20]:
Binary_Categoricals = ['Maternal Nativity','Paternity Acknowledged','Marital Status', 'WIC','Pre-pregnancy Diabetes', 
                      'Gestational Diabetes', 'Pre-pregnancy Hypertension', 'Gestational Hypertension',
                      'Hypertension Eclampsia', 'Previous Preterm Birth','Infertility treatment used', 'Fertility Enhancing Drugs', 
                      'Asst. Reproductive Tech', 'Gonorrhea', 'Syphilis', 'Chlamydia', 'Hep B', 'Hep C',
                      'Successful External Cephalic Version', 'Failed Cephalic Version','Induced Labor', 'Augmented Labor', 
                      'Steroids', 'Antibiotics', 'Chorioamnionitis', 'Anesthesia','If Cesarean, Labor Attempted',
                      'Maternal Transfusion', 'Perineal Laceration', 'Ruptured Uterus', 'Unplanned Hysterectomy',
                      'Maternal admit to ICU', 'Mother Transferred','infant sex','Assisted Ventilation immediately',
                      'Assisted ventilation >6hr', 'Admission to NICU', 'Surffactant', 'Antibiotis for Newborn', 'Seizures',
                      'Anencephaly', 'Spina Bifida', 'Cyanotic Congenital Heart Disease', 'Congenital Diaphragmatic Hernia',
                      'Omphalocele', 'Gastroschisis', 'Limb Reduction Defect', 'Cleft lip', 'Cleft Palate', 'Down Syndrome',
                      'Suspected Chromosomal Disorder', 'Hypospadias', 'Infant Transferred', 'Infant Living', 'Infant Breastfed']
Ordered_Categoricals = ['Maternal Education','Paternal Education','Month prenatal care Began']
Unordered_Categoricals = ['Birth Place','Maternal Residence Status','Maternal Race','Maternal Hispanic Origin', 
                         'Paternal Race', 'Paternal Hispanic Origin', 'Fetal Presentation at Delivery','Delivery Method',
                         'Attendant at Birth','Payment Source']
Numeric = ['Maternal Age','Paternal Age','Prior births, now living', 'Prior births, now dead', 'Prior terminations',
          'Interval since last Live Birth (Mo)', 'Number of Prenatal Visits','Daily Cigarette use before Pregnancy', 
           'Daily Cigarette use, 1st Trimester','Daily Cigarette use, 2nd Trimester', 'Daily Cigarette use, 3rd Trimester',
          'BMI', 'Weight Gain', 'Number of Previous Cesareans','5 Minute APGAR', '10 Minute APGAR', 'Plurality (Number of Babies)',
          'Gestation Duration (wks)', 'Birth Weight (g)']

Great! The data is in good shape for exploration! I will save it as a csv and move on to that step!

In [21]:
#note: due to restrictions on github, data needed to be split into smaller files in order to upload
df1 = df[:724417]
df2= df[724417:1448835]
df3 = df[1448835:2173252]
df4 = df[2173252:]

df1.to_csv('./NatalityData_cleaned_1.csv')
df2.to_csv('./NatalityData_cleaned_2.csv')
df3.to_csv('./NatalityData_cleaned_3.csv')
df4.to_csv('./NatalityData_cleaned_4.csv')

In [22]:
end_time = time.time()

print('Runtime: '+ str((end_time - start_time)/60) + ' minutes')

Runtime: 3.751729190349579 minutes